name: Daily News Agent

on:
  schedule:
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '30 18 * * *'  # 12:00 AM IST
  workflow_dispatch:         # Lets you trigger manually too

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run News Agent
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          
        run: python main.py
